--- 
- hosts: mywebservers
  become: yes 
  gather_facts: yes 
  tasks: 
  - name: i want to install apache2 
    apt: 
       name: "{{mywebpackonubuntu}}" 
       state: present 
    when: ansible_os_family =="Debian"

  - name: i want start apache2 
    service:
       name: "{{mywebpackonubuntu}}" 
       state: restarted        
    when: ansible_os_family =="Debian"


  - name: i want to install webserver on redhat nodes   
    yum: 
      name: "{{mywebpackageredhat}}" 
      state: present 
    when: ansible_os_family =="Redhat" 

  - name: i want to start webserver 
    service: 
      name: "{{mywebpackageredhat}}"
      state: started 
    when: ansible_os_family =="Redhat"     