--- 
- hosts: 172.31.31.73 
  become: yes 
  tasks: 
   - include_tasks: myfiles.yml
   - name: i want to install webservers 
     apt: 
      name: apache2 
      state: present 


   - name: i want to copy static files into ansible nodes side
     templates: 
       src: mystaticfile.html
       dest: /var/www/html/index.html   

   