--- 
- hosts: 172.31.31.73 
  become: yes 
  tasks: 
  - name: i want to execute direct linux command
    command: hostname -f
    
  - name: i want to display first task result
    debug: 
      msg: "{{myresult}}"  